# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :create_app_store_screenshots do
    frameit(
      path: "../integration_test/screenshots/ios/iPhone14ProMax",
      force_device_type: "iPhone 13 Pro Max",
      force_orientation_block: proc do |filename|
        f = filename.downcase
        if f.include?("landscape")
          :landscape_right
        end
      end
    )
  end
end
